Clearing in DHCP
CiscoTestAutomation/genielibs pull request #144
Opened 2023-11-20 20:01 UTC by joabda

Fixing error messages in existing clear.
Adding new clear for DHCP Snooping statistics.

2023-11-28 19:08 UTC, ThomasJRyan requested changes
Thank you for this new API. We'll need a changelog and unittest to get this merged in!

2023-11-28 19:08 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/dhcp/execute.py
> +    log.info("Executing clear_ip_dhcp_snooping_statistics API")
```suggestion
    log.debug("Executing clear_ip_dhcp_snooping_statistics API")

```

2023-11-29 15:19 UTC, joabda commented
> Thank you for this new API. We'll need a changelog and unittest to get this merged in!

Could you explain to me how to perform these please? First time adding new CLI.

2023-11-29 19:05 UTC, ThomasJRyan commented
Closing due to internal matters

2023-11-29 19:05 UTC, closed without merging