Add verify.py for iosxe eigrp folder containing 02 APIs for EIGRPv4 and EIGRPv6
CiscoTestAutomation/genielibs pull request #156
Opened 2024-03-05 18:50 UTC by cherifimehdi

Hello,

I noticed there is no verify.py file and verify apis for ios/iosxe eigrp protocol

I added verify.py file at pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp containing 02 APIs for EIGRPv4 and EIGRPv6:

        * verify_eigrp_interfaces
	    * verify_eigrp_neighbors

I added all the tests at pkgs/sdk-pkg/src/genie/libs/sdk/apis/tests/iosxe/eigrp/verify containing the test results for the 02 APIs in verify.py

I added the changelog_add_eigrp_verify.py_apis_202405031904 file at pkgs/sdk-pkg/changelog folder

Thank you for reviewing my contribution

2024-03-05 19:53 UTC, cherifimehdi commented
Hello @ThomasJRyan @Lelor can you please tell me why there is a problem in test step?  there is Some checks were not successful but for me it is OK since I added previously get.py for EIGRP without any problem. Thank you

2024-03-05 21:08 UTC, ThomasJRyan commented
![image](https://github.com/CiscoTestAutomation/genielibs/assets/18319621/3d62371b-59ad-44db-afdc-57296bd44352)

Looks to be caused by your branch being out of date. We're currently on version 24.2. Pull the latest `master` branch into yours and all should be good in the world

2024-03-06 16:22 UTC, ThomasJRyan requested changes
Thank you for the contribution. Unfortunately I think this PR will need some work before we can merge it in

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +               log.error(f"Sorry,no data for the provided 'AS = {AS_N}' and/or 'vrf = {vrf}' !")
I think we'd want to return `False` here?
```suggestion
               log.error(f"Sorry,no data for the provided 'AS = {AS_N}' and/or 'vrf = {vrf}' !")
               return False
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +            Result = set(interfaces_list).issubset(interfaces)
Actually, at this point I think we can just return no? No need to set a variable
```suggestion
            return set(interfaces_list).issubset(interfaces)
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +            timeout.sleep()
I think this would fit better under your `SchemaEmptyParserError`

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +         log.error(f"Please, provide a valide format for AS, interfaces_list, ip and/or vrf!!")
```suggestion
         log.error(f"Please, provide a valid format for AS, interfaces_list, ip and/or vrf")
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        Neighbors = None (list): Active EIGRP neighbors to check
This isn't in the correct order, and you're missing `max_time` and `check_interval`

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        Neighbors = None (list): Active EIGRP neighbors to check
Also, it should be `neighbors`

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +      if ((isinstance(AS_N, int) and isinstance(Neighbors, list) and isinstance(vrf, str) and AS_N != 0 and ip in ['ipv4','ipv6'])):
Same thing about being `assert`s and outside the loop

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +         log.error(f"Please, provide a valide format for AS, Neighbors, ip and/or vrf!!!!")
```suggestion
         log.error(f"Please, provide a valid format for AS, Neighbors, ip and/or vrf")
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +         if AS_N and  Neighbors:
Same thing about moving this out the loop

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +               return None
`continue` or return `False`

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +            else:
Since you're returning in the previous line, you don't need this `else`

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +               return None
```suggestion
               return False
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +            Result = set(Neighbors).issubset(eigrp_neighbors)
```suggestion
            return set(Neighbors).issubset(eigrp_neighbors)
```

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +               eigrp_neighbors = response.q.contains_key_value("eigrp_instance",str(AS_N)).contains(vrf).contains(ip).get_values("eigrp_nbr")
Any reason to not just do
```suggestion
               eigrp_neighbors = response.q.get_values("eigrp_nbr")
```
?

2024-03-06 16:22 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +               interfaces = response.q.contains(vrf).contains_key_value("eigrp_instance", str(AS_N)).contains(ip).get_values('interface')
Any reason to not just do
```suggestion
               interfaces = response.q.get_values('interface')
```
?

2024-03-06 19:26 UTC, cherifimehdi commented
Hi @ThomasJRyan, thanks for reviewing my PR. I went through all the changes and tested it, it works perfectly.
Thanks for reviewing my post.

2024-03-08 07:49 UTC, cherifimehdi commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
Hi @ThomasJRyan I fixed all the issues. Thank you

2024-03-09 09:23 UTC, cherifimehdi commented
Hello @ThomasJRyan @Lelor @Sohan are the changes I made ok. Because I addressed all them. Thank you

2024-03-11 15:42 UTC, cherifimehdi commented
Hi @ThomasJRyan are the changes I made ok based on your review? Thanks

2024-03-12 09:33 UTC, cherifimehdi commented
Hello @ThomasJRyan Thank you for your valuable comments. Now I used Black instead of Pylint and normally it is reformatted. I have made all the necessary changes based on your suggestions and feedback. Thanks for reviewing my PR

2024-03-12 17:13 UTC, ThomasJRyan approved these changes
Small things, but nothing worth blocking the PR further over. Thank you for the contribution!

2024-03-12 17:13 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        timeout.sleep()
These timeouts should be removed

2024-03-12 17:13 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        timeout.sleep()
Same with these ones

2024-03-12 17:13 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        if AS_N and interfaces_list:
This could also be an assertion

2024-03-12 17:13 UTC, ThomasJRyan commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        if AS_N and neighbors:
Same

2024-03-12 20:19 UTC, cherifimehdi commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        timeout.sleep()
I removed the timeout.sleep()

2024-03-12 20:19 UTC, cherifimehdi commented on pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/eigrp/verify.py
> +        timeout.sleep()
I removed the timeout.sleep()

2024-03-12 20:27 UTC, cherifimehdi commented
Hi @ThomasJRyan Thank you very much for your valuable remarks and taking time to review my PR and accepting my contribution.
By the way I addressed the suggested changes on timeout.sleep().
Thank you sir

2024-03-12 21:14 UTC, ThomasJRyan commented
No problem! I'll get @Lelor on this review as soon as possible so we can get you all merged in

2024-03-13 17:05 UTC, Lelor approved these changes

2024-03-13 19:54 UTC, merged